output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

output "workers_asg_arns" {
  description = "The AWS ASG ARNs for EKS cluster."
  value       = module.eks.workers_asg_arns
}

output "main_vpc_id" {
  value = module.main_vpc.vpc_id
  description = "VPC ID"
}

output "main_subnet_ids" {
  value = module.main_vpc.subnet_ids
  description = "Subnets IDs. To get id for one of subnet use next string module.MODULE_NAME.subnet_ids[NAME_OF_SUBNET]"
}
output "main_subnet_ipv4" {
  value = module.main_vpc.subnet_ipv4
  description = "Subnets IDs. To get id for one of subnet use next string module.MODULE_NAME.subnet_ipv4[NAME_OF_SUBNET]"
}